services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elifoot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    entrypoint: ["sh", "/usr/src/app/entrypoint.sh"]  # runs `npx prisma migrate reset --force` then `npm run start`
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/elifoot
      - PORT=4000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      disable: true
      test: ["CMD-SHELL", "curl -f http://localhost:4000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  postgres_data:
